import Head from 'next/head';
import { Inter } from '@next/font/google';

// Components
import SearchBox from '@/components/SearchBox';

// MUI
import { styled } from "@mui/material/styles";
import Container from '@mui/material/Container';

// Font
const inter = Inter({ subsets: ['latin'] })

// Styled components
const HomeWrapper = styled('main')(({ theme }) => ({
  height: '100vh',
  position: 'relative',
  overflow: 'hidden'
}));
const BGVideo = styled('video')(({ theme }) => ({
  position: 'absolute',
  left: 0,
  top: 0,
  width: '100%',
  height: '100%',
  zIndex: '-1',
  objectFit: 'cover'
}));
const Title = styled('h1')(({ theme }) => ({
  color: '#fff',
  maxWidth: 490,

  span: {
    fontSize: 68,
    lineHeight: 0.85
  },
  p: {
    margin: '8px 0 0',
    fontSize: 18,
    maxWidth: '80%'
  }
}));

/**
 * Custom styles
 * CS refers to custom styles
 */
const containerCS = {
  display: 'flex',
  flexWrap: 'wrap',
  alignItems: 'center',
  justifyContent: 'space-between',
  height: '100%'
};

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Mozio App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeWrapper className={inter.className}>
        <Container fixed sx={containerCS}>
          <Title>
            <span>Mozio Distance Calculator</span>
            <p>Calculate distance between cities accurately.</p>
          </Title>
          <SearchBox />
        </Container>
        <BGVideo
          autoPlay
          muted
          loop
          src="/assets/video/bg.mp4"
        />
      </HomeWrapper>
    </>
  )
}
